# Test Installation and Setup of SQL Servers
---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  custom_options: <%= ENV['PUPPET_COLOR'] %>
  puppet_debug: <%= ENV['PUPPET_DEBUG'] %>
  manifests_path: spec/manifests
  modules_path: .kitchen-modules
  require_chef_for_busser: false
  resolve_with_librarian_puppet: false
  puppet_detailed_exitcodes: true
  require_puppet_collections: true
  puppet_detailed_exitcodes: true
  max_retries: 5
  wait_for_retry: 40
  retry_on_exit_code:
    - 2 # The run succeeded, and some resources were changed.
    - 6 # The run succeeded, and included both changes and failures.

transport:
  name: winrm
  elevated: true

verifier:
  name: shell

platforms:
  - name: windows-2012r2
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2012r2
  - name: windows-2019
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2019
      provision: true
      vagrantfiles:
        - spec/vagrantfile.rb

suites:
  - name: sqlserver2008sp4
    excludes:
      - windows-2019
    provisioner:
      manifest: sqlserver2008sp4_2_instances.pp
      custom_facts:
        sqlserver2008_iso_url: <%= ENV['SQLSERVER2008_ISO_URL'] %>
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2008sp4_2_instances_spec.rb
  - name: sqlserver2012sp3
    excludes:
      - windows-2019
    provisioner:
      manifest: sqlserver2012sp3_2_instances.pp
      custom_facts:
        sqlserver2012_iso_url: <%= ENV['SQLSERVER2012_ISO_URL'] %>
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2012sp3_2_instances_spec.rb
  - name: sqlserver2014sp2
    excludes:
      - windows-2019
    provisioner:
      manifest: sqlserver2014sp2_2_instances.pp
      custom_facts:
        sqlserver2014_iso_url: <%= ENV['SQLSERVER2014_ISO_URL'] %>
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2014sp2_2_instances_spec.rb
  - name: sqlserver2016sp1
    excludes:
      - windows-2012r2
    provisioner:
      manifest: sqlserver2016sp1_2_instances.pp
      custom_facts:
        sqlserver2016_iso_url: <%= ENV['SQLSERVER2016_ISO_URL'] %>
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2016sp1_2_instances_spec.rb
  - name: sqlserver2017multiple
    excludes:
      - windows-2012r2
    provisioner:
      manifest: sqlserver2017rtm_2_instances.pp
      custom_facts:
        sqlserver2017_iso_url: <%= ENV['SQLSERVER2017_ISO_URL'] %>
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2017rtm_2_instances_spec.rb
  - name: sqlserver2019multiple
    excludes:
      - windows-2012r2
    provisioner:
      manifest: sqlserver2019rtm_2_instances.pp
      custom_facts:
        sqlserver2019_iso_url: <%= ENV['SQLSERVER2019_ISO_URL'] %>
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2019rtm_2_instances_spec.rb
  - name: sqlserver2022multiple
    excludes:
      - windows-2012r2
    provisioner:
      manifest: sqlserver2022ctp_2_instances.pp
      custom_facts:
        sqlserver2022_iso_url: <%= ENV['SQLSERVER2022_ISO_URL'] %>
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/sqlserver2022ctp_2_instances_spec.rb
