# Test installations of SSMS
---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  custom_options: <%= ENV['PUPPET_COLOR'] %>
  puppet_debug: <%= ENV['PUPPET_DEBUG'] %>
  manifests_path: spec/manifests
  modules_path: .kitchen-modules
  require_chef_for_busser: false
  resolve_with_librarian_puppet: false
  puppet_detailed_exitcodes: true
  require_puppet_collections: true
  puppet_detailed_exitcodes: true
  max_retries: 3
  wait_for_retry: 40
  retry_on_exit_code:
    - 2 # The run succeeded, and some resources were changed.
    - 6 # The run succeeded, and included both changes and failures.

transport:
  name: winrm
  elevated: true

verifier:
  name: shell

platforms:
  - name: windows-2019
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2019
      box_url: https://vagrant.red-gate.com/red-gate/windows-2019
      provision: true
      vagrantfiles:
        - spec/vagrantfile.rb

suites:
  - name: localdbs
    provisioner:
      manifest: localdbs.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/localdbs_spec.rb
  - name: ssms2016
    provisioner:
      manifest: ssms2016.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/ssms2016_spec.rb
  - name: ssms2017
    provisioner:
      manifest: ssms2017.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/ssms2017_spec.rb
  - name: ssms2018
    provisioner:
      manifest: ssms2018.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/ssms2018_spec.rb
  - name: ssms19
    provisioner:
      manifest: ssms19.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/ssms19_spec.rb
